[tools]
neovim = "0.10"
node = "22"
pnpm = "latest"
deno = "latest"
ruby = "3.3.5"
redis = "6.2.17"
go = "1.23.2"
python = "3.13.0"
elixir = "1.18.2-otp-27"
erlang = "27.3"
watchexec = "latest"

[settings]
experimental = true
