-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--

-- local ls = require("luasnip")

-- -------------------------------------------------
-- LuaSnip choice_node keymaps
-- REF: https://www.reddit.com/r/neovim/comments/tbtiy9/comment/i0bje36/
-- -------------------------------------------------
-- vim.keymap.set({ "i", "s" }, "<C-l>", function()
--   if ls.choice_active() then
--     ls.change_choice(1)
--   end
-- end, { silent = true })
--
-- vim.keymap.set({ "i", "s" }, "<C-h>", function()
--   if ls.choice_active() then
--     ls.change_choice(-1)
--   end
-- end, { silent = true })

-- vim.keymap.set({ "i", "s" }, "<A-k>", function()
--   if ls.expand_or_jumpable() then
--     ls.expand_or_jump()
--   end
-- end, { silent = true })
--
-- vim.keymap.set({ "i", "s" }, "<A-j>", function()
--   if ls.jumpable(-1) then
--     ls.jump(-1)
--   end
-- end, { silent = true })
